apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
  namespace: {{ .Values.cassandra.namespace }}
  labels:
    app: cassandra
data:
  cassandra.yaml: |
    # Cassandra Configuration
    cluster_name: {{ .Values.cassandra.cluster_name }}
    listen_address: "{$POD_IP}"
    broadcast_address: "{$POD_IP}"
    broadcast_rpc_address: "{$POD_IP}"
    rpc_address: 0.0.0.0
    cassandra_port: {{ .Values.cassandra.cassandra_port }}
    num_tokens: {{ .Values.cassandra.numTokens }}
    data_file_directories: {{ .Values.cassandra.data_Dir }}
    commitlog_directory: {{ .Values.cassandra.commitlogDir }}
    saved_caches_directory: {{ .Values.cassandra.cacheDir }}
    seeds_address: "{{ .Values.cassandra.seeds }}"
    internode_encryption: none
    truststore_directory: /etc/cassandra/cs_trust
    keystore: {{ .Values.cassandra.keystore_directory }}
    truststore: {{ .Values.cassandra.truststore_directory }}
    hinted_handoff_enabled: true
    concurrent_reads: {{ .Values.cassandra.concurrent_reads }}
    concurrent_writes: {{ .Values.cassandra.concurrent_writes }}
    native_transport_port: {{ .Values.cassandra.cassandra_port }}
    phi_convict_threshold: {{ .Values.cassandra.phi_convict_threshold }}

  cassandra-rackdc.properties: |
    dc: {{ .Values.cassandra.datacenter_name }}
    rack: Rack{{ .Values.cassandra.racknum }}