apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.cassandra.namespace }}
  labels:
    app: cassandra
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: intra
    port: 7000
    targetPort: 7000
  - name: tls
    port: 7001
    targetPort: 7001
  - name: jmx
    port: 7199
    targetPort: 7199
  - name: cql
    port: {{ .Values.cassandra.cassandra_port }}
    targetPort: {{ .Values.cassandra.cassandra_port }}
  - name: thrift
    port: {{ .Values.cassandra.thrift_port }}
    targetPort: {{ .Values.cassandra.thrift_port }}
  - name: agent
    port: 61621
    targetPort: 61621