apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-script
  namespace: {{ .Values.cassandra.namespace }}
  labels:
    app: cassandra
data:
  script.sh: |
    #!/bin/bash
    CONFIG_FILE="/tmp/writable/cassandra.yaml"
    TARGET_FILE="/tmp/writable/cassandra-main.yaml"

    if [ -f "$CONFIG_FILE" ]; then
      echo "Applying configuration overrides from $CONFIG_FILE"

      while IFS= read -r line; do
        [[ -z "$line" || "$line" =~ ^# ]] && continue

        key=$(echo "$line" | cut -d ':' -f1 | xargs)
        value=$(echo "$line" | cut -d ':' -f2- | xargs) # Use '-f2-' to capture the whole value

        if [ -n "$key" ] && [ -n "$value" ]; then
          # Escape special characters for sed
          escaped_key=$(printf '%s' "$key" | sed 's/[\/&]/\\&/g')
          escaped_value=$(printf '%s' "$value" | sed 's/[\/&]/\\&/g')

          # Replace the key's value, ensuring to match lines starting with the key
          sed -i "s#^\s*${escaped_key}\s*:.*#${escaped_key}: ${escaped_value}#" "$TARGET_FILE"
        fi
      done < "$CONFIG_FILE"
    else
      echo "Configuration file $CONFIG_FILE not found"
    fi